export const studyGroups = [
  {
    StudyGroupId: 1,
    GroupName: "Physics Prodigies",
    Rating: 4.2,
    TeacherExperienceYears: 8,
    Subject: "Physics",
    TeacherName: "Rajesh Kumar",
    Location: "Mumbai",
    GroupCode: "3R7K9L",
    Description: "Brilliant minds mastering the laws of the universe.",
    ImageURL:
      "https://images.pexels.com/photos/714698/pexels-photo-714698.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    DetailedDescription:
      "Our physics chat group offers a platform for students to discuss various topics in physics, ranging from classical mechanics to quantum mechanics, electromagnetism, thermodynamics, and beyond. Whether you're struggling with understanding the laws of motion or unraveling the complexities of particle physics, our community is here to help. Through chat and video calls, you can engage in lively discussions, seek clarification on concepts, and collaborate with peers to deepen your understanding of the subject.",
    Topics: [
      "classical mechanics",
      "quantum mechanics",
      "electromagnetism",
      "thermodynamics",
      "particle physics",
    ],
  },
  {
    StudyGroupId: 2,
    GroupName: "Chemistry Champions",
    Rating: 4.8,
    TeacherExperienceYears: 10,
    Subject: "Chemistry",
    TeacherName: "Priya Sharma",
    Location: "Delhi",
    GroupCode: "H2V6XE",
    Description: "Exploring the elements and reactions that shape our world.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2014/04/05/11/40/water-316625_1280.jpg",
    DetailedDescription:
      "Dive into the world of atoms and molecules with our chemistry chat. From chemical reactions to atomic structure, our experts are here to guide you. Discuss organic, inorganic, and physical chemistry topics with peers. Our video call feature ensures visual demonstrations for complex reactions and experiments.",
    Topics: [
      "chemical reactions",
      "atomic structure",
      "organic chemistry",
      "inorganic chemistry",
      "physical chemistry",
    ],
  },
  {
    StudyGroupId: 3,
    GroupName: "Math Masters",
    Rating: 4.5,
    TeacherExperienceYears: 6,
    Subject: "Math",
    TeacherName: "Anil Singh",
    Location: "Bangalore",
    GroupCode: "5Y9GQW",
    Description:
      "Delving into the depths of mathematical theory and application.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2017/05/24/08/49/mathematics-2339904_1280.jpg",
    DetailedDescription:
      "Explore the depths of calculus, algebra, geometry, and more in our mathematics chat. Solve equations, unravel the mysteries of calculus, and explore the beauty of proofs. Engage in lively discussions on mathematical concepts with fellow enthusiasts. Our video call feature allows for interactive problem-solving sessions.",
    Topics: ["calculus", "algebra", "geometry", "proofs"],
  },
  {
    StudyGroupId: 4,
    GroupName: "Biology Buffs",
    Rating: 4,
    TeacherExperienceYears: 9,
    Subject: "Biology",
    TeacherName: "Sunita Patel",
    Location: "Kolkata",
    GroupCode: "J4C8FN",
    Description: "Investigating the intricate workings of living organisms.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2022/03/25/12/17/skeleton-7090995_960_720.jpg",
    DetailedDescription:
      "Embark on a journey through the wonders of life sciences in our biology chat. From cell biology to ecology, our experts provide insights into diverse biological topics. Engage in discussions on genetics, physiology, and evolution with like-minded individuals. With video calls, observe live experiments and dissect specimens virtually.",
    Topics: ["cell biology", "ecology", "genetics", "physiology", "evolution"],
  },
  {
    StudyGroupId: 5,
    GroupName: "Coding Wizards",
    Rating: 4.3,
    TeacherExperienceYears: 7,
    Subject: "Coding",
    TeacherName: "Vivek Gupta",
    Location: "Chennai",
    GroupCode: "U1P5BS",
    Description: "Crafting solutions through the language of computers.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2016/11/19/14/00/code-1839406_960_720.jpg",
    DetailedDescription:
      "Join our coding chat to master programming languages and algorithms. From Python to Java, sharpen your coding skills with hands-on exercises and projects. Discuss data structures, algorithms, and software development techniques with peers and experts. Our video call feature facilitates live coding sessions and code reviews.",
    Topics: [
      "programming languages",
      "algorithms",
      "data structures",
      "software development techniques",
    ],
  },
  {
    StudyGroupId: 6,
    GroupName: "History Scholars",
    Rating: 4.6,
    TeacherExperienceYears: 11,
    Subject: "History",
    TeacherName: "Manisha Dubey",
    Location: "Hyderabad",
    GroupCode: "9Z6DAK",
    Description: "Unraveling the tapestry of human civilization.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2018/05/17/16/03/compass-3408928_1280.jpg",
    DetailedDescription:
      "Delve into the annals of human civilization in our history chat. Explore ancient civilizations, world wars, and cultural revolutions with fellow history enthusiasts. Engage in debates, share historical anecdotes, and gain insights into past events. With video calls, visualize historical maps and artifacts for a richer learning experience.",
    Topics: ["ancient civilizations", "world wars", "cultural revolutions"],
  },
  {
    StudyGroupId: 7,
    GroupName: "Geography Explorers",
    Rating: 4.1,
    TeacherExperienceYears: 5,
    Subject: "Geography",
    TeacherName: "Neha Mishra",
    Location: "Pune",
    GroupCode: "N8R3MG",
    Description: "Navigating the diverse landscapes of the world.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2017/08/15/11/10/globe-2643536_640.jpg",
    DetailedDescription:
      "Journey across the globe in our geography chat. Explore diverse landscapes, climates, and cultures with fellow geography buffs. Discuss topics ranging from physical geography to geopolitics and environmental studies. Our video call feature allows for virtual tours and map analysis, bringing geography to life.",
    Topics: ["physical geography", "geopolitics", "environmental studies"],
  },
  {
    StudyGroupId: 8,
    GroupName: "Physics Club",
    Rating: 4.7,
    TeacherExperienceYears: 12,
    Subject: "Physics",
    TeacherName: "Sunil Verma",
    Location: "Ahmedabad",
    GroupCode: "C5W1PY",
    Description: "Fostering a passion for physics within a community.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2018/12/12/17/08/physics-3871216_640.jpg",
    DetailedDescription:
      "Unravel the mysteries of the universe in our physics chat. From Newtonian mechanics to quantum theory, explore the fundamental laws governing our world. Engage in discussions on topics like optics, fluid dynamics, and particle physics. With video calls, visualize experiments and simulations to deepen your understanding.",
    Topics: [
      "Newtonian mechanics",
      "quantum theory",
      "optics",
      "fluid dynamics",
    ],
  },
  {
    StudyGroupId: 9,
    GroupName: "Chemistry Champions",
    Rating: 4.4,
    TeacherExperienceYears: 8,
    Subject: "Chemistry",
    TeacherName: "Anjali Tiwari",
    Location: "Surat",
    GroupCode: "Q7B2JV",
    Description: "Achieving excellence in the realm of chemistry.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2019/12/21/20/44/math-work-4711302_960_720.jpg",
    DetailedDescription:
      "Join our chemistry chat to explore the fascinating world of atoms and molecules. Dive into topics like chemical bonding, kinetics, and thermodynamics with fellow chemistry enthusiasts. Engage in discussions on practical applications in various fields, from medicine to materials science. Our video call feature enables virtual experiments and demonstrations.",
    Topics: [
      "chemical bonding",
      "kinetics",
      "thermodynamics",
      "applications in various fields",
    ],
  },
  {
    StudyGroupId: 10,
    GroupName: "Arithmetic Aces",
    Rating: 3.9,
    TeacherExperienceYears: 7,
    Subject: "Math",
    TeacherName: "Arjun Singh",
    Location: "Jaipur",
    GroupCode: "M9F4HE",
    Description: "Mastering the fundamentals of arithmetic with precision.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2013/11/28/09/50/albert-einstein-219675_640.jpg",
    DetailedDescription:
      "Join our math chat to embark on a journey of discovery and problem-solving. Explore topics like calculus, algebra, and number theory with like-minded individuals. Engage in discussions on mathematical puzzles, proofs, and applications in various fields. Our video call feature facilitates interactive problem-solving sessions and mathematical explorations.",
    Topics: [
      "calculus",
      "algebra",
      "number theory",
      "mathematical puzzles",
      "applications in various fields",
    ],
  },
  {
    StudyGroupId: 11,
    GroupName: "Cellular Scholars",
    Rating: 4.5,
    TeacherExperienceYears: 9,
    Subject: "Biology",
    TeacherName: "Amit Kumar",
    Location: "Lucknow",
    GroupCode: "T3N5YF",
    Description: "Delving into the microscopic wonders of cellular life.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2018/07/15/10/44/dna-3539309_1280.jpg",
    DetailedDescription:
      "Explore the wonders of life sciences in our biology chat. From cellular biology to ecology, delve into the diverse realms of living organisms. Engage in discussions on genetics, evolution, and environmental science with fellow enthusiasts. Our video call feature enables virtual dissections and field trip simulations for an immersive learning experience.",
    Topics: [
      "cellular biology",
      "ecology",
      "genetics",
      "evolution",
      "environmental science",
    ],
  },
  {
    StudyGroupId: 12,
    GroupName: "Code Crafters",
    Rating: 4.6,
    TeacherExperienceYears: 8,
    Subject: "Coding",
    TeacherName: "Rahul Sharma",
    Location: "Indore",
    GroupCode: "A2R6TK",
    Description: "Sculpting code into elegant and efficient solutions.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2016/11/30/20/58/programming-1873854_640.png",
    DetailedDescription:
      "Join our coding chat to master programming languages and algorithms. From web development to machine learning, explore a wide range of coding topics with peers and experts. Engage in discussions on software design, debugging techniques, and best coding practices. Our video call feature facilitates live coding sessions and collaborative projects.",
    Topics: [
      "programming languages",
      "web development",
      "machine learning",
      "software design",
      "debugging techniques",
    ],
  },
  {
    StudyGroupId: 13,
    GroupName: "World History Wizards",
    Rating: 4.3,
    TeacherExperienceYears: 10,
    Subject: "History",
    TeacherName: "Shivani Saxena",
    Location: "Varanasi",
    GroupCode: "F4D9ZQ",
    Description: "Journeying through the epochs of global history.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2015/11/19/21/11/knowledge-1052013_1280.jpg",
    DetailedDescription:
      "Embark on a journey through time in our history chat. Explore the rise and fall of civilizations, major historical events, and cultural transformations with fellow history enthusiasts. Engage in discussions on historical interpretations, primary sources, and historiography. With video calls, visualize historical artifacts and documents for a richer understanding.",
    Topics: [
      "ancient civilizations",
      "major historical events",
      "cultural transformations",
      "historical interpretations",
      "historiography",
    ],
  },
  {
    StudyGroupId: 14,
    GroupName: "Earth Explorers",
    Rating: 4.2,
    TeacherExperienceYears: 6,
    Subject: "Geography",
    TeacherName: "Aryan Patel",
    Location: "Nagpur",
    GroupCode: "G5W7QB",
    Description: "Discovering the secrets of our planet's geography.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2015/11/26/09/14/school-1063554_640.jpg",
    DetailedDescription:
      "Embark on a virtual journey across the globe in our geography chat. Explore diverse landscapes, climates, and cultures with fellow adventurers. Engage in discussions on topics like cultural geography, cartography, and geopolitical issues. Our video call feature allows for virtual tours and map analysis, bringing geography to life.",
    Topics: ["cultural geography", "cartography", "geopolitical issues"],
  },
  {
    StudyGroupId: 15,
    GroupName: "Quantum Quotients",
    Rating: 4.8,
    TeacherExperienceYears: 11,
    Subject: "Physics",
    TeacherName: "Neha Singh",
    Location: "Patna",
    GroupCode: "P6J2AC",
    Description: "Exploring the mysterious realms of quantum mechanics.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2022/01/14/07/50/physics-6936704_640.jpg",
    DetailedDescription:
      "Join our physics chat to explore the wonders of the universe. From classical mechanics to quantum theory, delve into the fundamental laws governing our world. Engage in discussions on topics like relativity, cosmology, and particle physics with fellow enthusiasts. With video calls, visualize experiments and simulations to deepen your understanding.",
    Topics: [
      "classical mechanics",
      "quantum theory",
      "relativity",
      "cosmology",
      "particle physics",
    ],
  },
  {
    StudyGroupId: 16,
    GroupName: "Chemical Connoisseurs",
    Rating: 4.1,
    TeacherExperienceYears: 7,
    Subject: "Chemistry",
    TeacherName: "Rajat Gupta",
    Location: "Bhopal",
    GroupCode: "U9K4TD",
    Description:
      "Diving into the complexities of chemical structures and reactions.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2018/02/10/11/43/hexagons-3143432_640.jpg",
    DetailedDescription:
      "Join our chemistry chat to unlock the secrets of atoms and molecules. Explore topics like chemical kinetics, equilibrium, and spectroscopy with peers and experts. Engage in discussions on applications in fields like medicine, materials science, and environmental chemistry. Our video call feature enables virtual experiments and demonstrations.",
    Topics: [
      "chemical kinetics",
      "equilibrium",
      "spectroscopy",
      "applications in fields like medicine",
      "materials science",
      "environmental chemistry",
    ],
  },
  {
    StudyGroupId: 17,
    GroupName: "Math Magicians",
    Rating: 4.7,
    TeacherExperienceYears: 12,
    Subject: "Math",
    TeacherName: "Pooja Sharma",
    Location: "Agra",
    GroupCode: "V4W9YN",
    Description: "Performing mathematical feats with precision and elegance.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2015/11/15/07/47/geometry-1044090_1280.jpg",
    DetailedDescription:
      "Join our math chat to explore the beauty of numbers and patterns. From algebraic geometry to mathematical logic, delve into diverse mathematical realms with peers and experts. Engage in discussions on mathematical modeling, problem-solving strategies, and real-world applications. With video calls, collaborate on challenging problems and discover new mathematical insights.",
    Topics: [
      "algebraic geometry",
      "mathematical logic",
      "mathematical modeling",
      "real-world applications",
    ],
  },
  {
    StudyGroupId: 18,
    GroupName: "Biological Brainiacs",
    Rating: 4.5,
    TeacherExperienceYears: 9,
    Subject: "Biology",
    TeacherName: "Aarti Gupta",
    Location: "Visakhapatnam",
    GroupCode: "R5N8ME",
    Description: "Delving into the depths of biological systems and processes.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2016/11/10/02/47/blood-1813410_640.jpg",
    DetailedDescription:
      "Join our biology chat to explore the wonders of living organisms. From molecular biology to ecology, delve into the fascinating realms of life sciences with peers and experts. Engage in discussions on genetics, evolution, and environmental sustainability. Our video call feature enables virtual dissections and interactive simulations for an immersive learning experience.",
    Topics: ["molecular biology", "physiology", "environmental sustainability"],
  },
  {
    StudyGroupId: 19,
    GroupName: "Coding Crusaders",
    Rating: 4.4,
    TeacherExperienceYears: 8,
    Subject: "Coding",
    TeacherName: "Rohan Kapoor",
    Location: "Ludhiana",
    GroupCode: "T8A7WP",
    Description: "Embarking on epic coding quests in the digital realm.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2017/08/10/08/47/laptop-2620118_640.jpg",
    DetailedDescription:
      "Join our coding chat to master programming languages and algorithms. From web development to artificial intelligence, explore a wide range of coding topics with peers and experts. Engage in discussions on software architecture, debugging techniques, and industry trends. Our video call feature facilitates live coding sessions and collaborative projects.",
    Topics: [
      "web development",
      "artificial intelligence",
      "software architecture",
      "industry trends",
    ],
  },
  {
    StudyGroupId: 20,
    GroupName: "Historical Heroes",
    Rating: 4.6,
    TeacherExperienceYears: 10,
    Subject: "History",
    TeacherName: "Sandeep Yadav",
    Location: "Kanpur",
    GroupCode: "Q6P3VH",
    Description: "Reviving the stories of history's most remarkable figures.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2015/10/20/19/38/history-998337_640.jpg",
    DetailedDescription:
      "Embark on a historical journey in our history chat. Explore ancient civilizations, major historical events, and cultural transformations with fellow history enthusiasts. Engage in discussions on historical narratives, artifacts, and global perspectives. With video calls, analyze primary sources and historical documents for a deeper understanding of the past.",
    Topics: [
      "ancient civilizations",
      "major historical events",
      "cultural transformations",
      "historical narratives",
      "global perspectives",
    ],
  },
  {
    StudyGroupId: 21,
    GroupName: "Geographic Geniuses",
    Rating: 4.3,
    TeacherExperienceYears: 6,
    Subject: "Geography",
    TeacherName: "Ruchi Sharma",
    Location: "Faridabad",
    GroupCode: "W2D5JL",
    Description: "Mapping out the wonders of our planet's geography.",
    ImageURL:
      "https://images.pexels.com/photos/592753/pexels-photo-592753.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    DetailedDescription:
      "Journey across the globe in our geography chat. Explore diverse landscapes, climates, and cultures with fellow geography buffs. Discuss topics ranging from physical geography to geopolitics and environmental studies. Our video call feature allows for virtual tours and map analysis, bringing geography to life.",
    Topics: ["physical geography", "human geography", "geopolitical issues"],
  },
  {
    StudyGroupId: 22,
    GroupName: "Physics Gamma",
    Rating: 4.5,
    TeacherExperienceYears: 9,
    Subject: "Physics",
    TeacherName: "Nidhi Verma",
    Location: "Agra",
    GroupCode: "Y1S5NC",
    Description: "Reaching the apex of physics knowledge and expertise.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2019/11/17/07/52/current-4631715_640.jpg",
    DetailedDescription:
      "Journey into the realm of matter, energy, and the fundamental forces of the universe in our physics chat. Engage in discussions on topics such as classical mechanics, electromagnetism, and quantum physics with experts and enthusiasts alike. With video calls, visualize complex phenomena and conduct virtual experiments for a deeper understanding.",
    Topics: ["classical mechanics", "electromagnetism", "quantum physics"],
  },
  {
    StudyGroupId: 23,
    GroupName: "Bonding Bosses",
    Rating: 4,
    TeacherExperienceYears: 7,
    Subject: "Chemistry",
    TeacherName: "Sanjay Gupta",
    Location: "Nashik",
    GroupCode: "8Z3KJP",
    Description: "Mastering the art of chemical bonding and interactions.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2013/11/24/11/10/lab-217043_640.jpg",
    DetailedDescription:
      "Explore the intricate dance of atoms and molecules in our chemistry chat. Delve into topics like chemical reactions, molecular structures, and the periodic table with fellow chemistry aficionados. Our video call feature facilitates virtual lab experiments and molecular modeling, allowing for hands-on exploration of chemical principles.",
    Topics: [
      "chemical reactions",
      "molecular structures",
      "the periodic table",
    ],
  },
  {
    StudyGroupId: 24,
    GroupName: "Statistics Stars",
    Rating: 4.3,
    TeacherExperienceYears: 10,
    Subject: "Math",
    TeacherName: "Pooja Sharma",
    Location: "Faridabad",
    GroupCode: "A5W1EU",
    Description: "Solving equations with speed and accuracy.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2016/06/13/07/59/pi-1453836_640.jpg",
    DetailedDescription:
      "Embark on a voyage of discovery through the abstract world of numbers and patterns in our mathematics chat. Discuss topics ranging from calculus and algebra to geometry and statistics with peers and mentors. With video calls, visualize mathematical concepts and engage in collaborative problem-solving sessions to unlock the beauty of mathematics.",
    Topics: ["calculus", "algebra", "geometry", "statistics"],
  },
  {
    StudyGroupId: 25,
    GroupName: "Evolutionary Explorers",
    Rating: 4.6,
    TeacherExperienceYears: 11,
    Subject: "Biology",
    TeacherName: "Vikas Yadav",
    Location: "Meerut",
    GroupCode: "P9B6HD",
    Description: "Immersing in the study of anatomical structures and systems.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2017/02/01/13/53/analysis-2030265_640.jpg",
    DetailedDescription:
      "Dive into the fascinating study of life in our biology chat. Explore topics such as genetics, ecology, and physiology with fellow biologists. Our video call feature enables virtual dissections, field trips, and microscopy sessions, providing immersive experiences to deepen your understanding of biological concepts.",
    Topics: ["genetics", "ecology", "physiology"],
  },
  {
    StudyGroupId: 26,
    GroupName: "Tech Titans",
    Rating: 4.1,
    TeacherExperienceYears: 5,
    Subject: "Coding",
    TeacherName: "Sarika Singh",
    Location: "Rajkot",
    GroupCode: "T3G7MQ",
    Description: "Pioneering breakthroughs in coding and software development.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2016/11/19/22/52/coding-1841550_640.jpg",
    DetailedDescription:
      "Unlock the secrets of programming languages and algorithms in our coding chat. From Python to Java, delve into coding challenges and projects with guidance from experienced programmers. With video calls, engage in live coding sessions and code reviews, accelerating your journey towards becoming a proficient coder.",
    Topics: ["programming languages", "algorithms", "debugging techniques"],
  },
  {
    StudyGroupId: 27,
    GroupName: "History Scholars",
    Rating: 4.8,
    TeacherExperienceYears: 12,
    Subject: "History",
    TeacherName: "Gaurav Sharma",
    Location: "Varanasi",
    GroupCode: "R6L2FX",
    Description: "Tracing the footsteps of historical events and figures.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2017/07/22/11/46/adventure-2528477_640.jpg",
    DetailedDescription:
      "Travel through the corridors of time in our history chat, where you'll explore the events and personalities that shaped our world. Discuss ancient civilizations, world wars, and cultural movements with fellow history enthusiasts. With video calls, analyze historical documents and artifacts, gaining insight into the complexities of human history.",
    Topics: [
      "ancient civilizations",
      "major historical events",
      "cultural movements",
      "historical narratives",
      "primary sources",
    ],
  },
  {
    StudyGroupId: 28,
    GroupName: "Geography Explorers",
    Rating: 4.5,
    TeacherExperienceYears: 9,
    Subject: "Geography",
    TeacherName: "Shalini Tiwari",
    Location: "Srinagar",
    GroupCode: "K1N5CV",
    Description: "Charting the terrains of our planet and beyond.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2015/01/15/16/17/hands-600497_1280.jpg",
    DetailedDescription:
      "Embark on a global odyssey in our geography chat, where you'll explore the diverse landscapes and cultures of our planet. Discuss topics like physical geography, human geography, and geopolitical issues with fellow adventurers. Our video call feature enables virtual field trips and map analysis, bringing geography to life in vivid detail.",
    Topics: ["physical geography", "human geography", "geopolitical issues"],
  },
  {
    StudyGroupId: 29,
    GroupName: "Physics Omega",
    Rating: 4.3,
    TeacherExperienceYears: 7,
    Subject: "Physics",
    TeacherName: "Rajeev Verma",
    Location: "Aurangabad",
    GroupCode: "F4U9ZA",
    Description: "Delving into the depths of quantum mechanics.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2016/03/01/10/55/mathematics-1230074_640.jpg",
    DetailedDescription:
      "Join our physics chat to unravel the mysteries of the cosmos, from the tiniest subatomic particles to the vast expanse of space-time. Engage in lively discussions on topics like mechanics, optics, and quantum theory with experts and peers. With video calls, witness simulations and experiments firsthand, making abstract concepts tangible.",
    Topics: ["classical mechanics", "optics", "quantum theory"],
  },
  {
    StudyGroupId: 30,
    GroupName: "Reaction Rangers",
    Rating: 4.6,
    TeacherExperienceYears: 10,
    Subject: "Chemistry",
    TeacherName: "Sandhya Gupta",
    Location: "Dhanbad",
    GroupCode: "2R7V8C",
    Description: "Dominating the periodic table and chemical reactions.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2015/04/26/13/47/chemistry-740453_640.jpg",
    DetailedDescription:
      "Immerse yourself in the fascinating world of atoms and molecules in our chemistry chat. Explore topics such as chemical bonding, kinetics, and thermodynamics with fellow enthusiasts. Our video call feature allows for virtual lab experiments and molecular modeling, providing hands-on learning experiences from the comfort of your home.",
    Topics: [
      "chemical bonding",
      "kinetics",
      "thermodynamics",
      "virtual lab experiments",
      "molecular modeling",
    ],
  },
  {
    StudyGroupId: 31,
    GroupName: "Function Fanatics",
    Rating: 4.2,
    TeacherExperienceYears: 6,
    Subject: "Math",
    TeacherName: "Ananya Singh",
    Location: "Amritsar",
    GroupCode: "W6D2FB",
    Description: "Tackling mathematical problems with precision.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2016/11/29/01/16/abacus-1866497_640.jpg",
    DetailedDescription:
      "Embark on a journey of discovery through the language of patterns and logic in our mathematics chat. Dive deep into topics like calculus, algebra, and discrete mathematics with peers and mentors. With video calls, visualize complex concepts and engage in collaborative problem-solving sessions, honing your mathematical skills.",
    Topics: ["calculus", "algebra", "discrete mathematics"],
  },
  {
    StudyGroupId: 32,
    GroupName: "Ecology Enthusiasts",
    Rating: 4.7,
    TeacherExperienceYears: 11,
    Subject: "Biology",
    TeacherName: "Sumit Sharma",
    Location: "Navi Mumbai",
    GroupCode: "9X5NPJ",
    Description: "Exploring the wonders of evolution and adaptation.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2016/11/30/12/17/cells-1872666_640.jpg",
    DetailedDescription:
      "Explore the wonders of life on Earth in our biology chat. Discuss topics such as genetics, ecology, and anatomy with fellow biologists. Our video call feature enables virtual dissections and field trips, bringing the intricacies of the natural world into focus. Join us to unravel the mysteries of living organisms together.",
    Topics: ["genetics", "ecology", "anatomy"],
  },
  {
    StudyGroupId: 33,
    GroupName: "CodeCrafters",
    Rating: 4.4,
    TeacherExperienceYears: 8,
    Subject: "Coding",
    TeacherName: "Deepika Tiwari",
    Location: "Allahabad",
    GroupCode: "C7Q3GL",
    Description: "Leading the charge in technological advancements.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2014/05/27/23/32/matrix-356024_640.jpg",
    DetailedDescription:
      "Master the art of programming in our coding chat, where you'll learn to speak the language of computers fluently. From algorithms to web development, delve into coding challenges and projects with guidance from experienced programmers. With video calls, engage in live coding sessions and code reviews, accelerating your journey towards becoming a proficient coder.",
    Topics: ["algorithms", "web development"],
  },
  {
    StudyGroupId: 34,
    GroupName: "History Scholars",
    Rating: 4.1,
    TeacherExperienceYears: 5,
    Subject: "History",
    TeacherName: "Mohit Sharma",
    Location: "Ranchi",
    GroupCode: "H1M6DY",
    Description:
      "Deepening understanding of past events and their implications.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2018/01/28/17/48/gallery-3114279_640.jpg",
    DetailedDescription:
      "Step into the past and explore the tapestry of human civilization in our history chat. Delve into ancient cultures, pivotal events, and influential figures with fellow history enthusiasts. With video calls, analyze primary sources and historical artifacts, gaining a deeper understanding of the forces that shaped our world.",
    Topics: ["ancient cultures", "pivotal events"],
  },
  {
    StudyGroupId: 35,
    GroupName: "Geography Explorers",
    Rating: 4.8,
    TeacherExperienceYears: 12,
    Subject: "Geography",
    TeacherName: "Sonal Verma",
    Location: "Howrah",
    GroupCode: "4T9LBS",
    Description: "Embarking on a journey through the cosmos.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2017/06/14/08/20/map-of-the-world-2401458_640.jpg",
    DetailedDescription:
      "Embark on a virtual journey around the globe in our geography chat. Explore diverse landscapes, climates, and cultures while discussing topics such as physical geography, human geography, and geopolitics with peers. Our video call feature enables interactive map analysis and virtual field trips, bringing the world to your fingertips.",
    Topics: ["physical geography", "human geography", "geopolitics"],
  },
  {
    StudyGroupId: 36,
    GroupName: "Physics Pyramid",
    Rating: 4.5,
    TeacherExperienceYears: 9,
    Subject: "Physics",
    TeacherName: "Rohit Kumar",
    Location: "Coimbatore",
    GroupCode: "Z8E2WQ",
    Description: "Crusading for advancements in chemical science.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2018/01/13/10/20/pulse-3079902_640.jpg",
    DetailedDescription:
      "Join our physics chat to journey through the universe's fundamental laws and phenomena. From classical mechanics to modern theories, explore topics like relativity, quantum mechanics, and electromagnetism with experts and enthusiasts. With video calls, visualize experiments and simulations, fostering a deeper understanding of the intricacies of the cosmos.",
    Topics: [
      "classical mechanics",
      "modern theories",
      "relativity",
      "quantum mechanics",
      "electromagnetism",
    ],
  },
  {
    StudyGroupId: 37,
    GroupName: "Chemical Crusaders",
    Rating: 4.3,
    TeacherExperienceYears: 7,
    Subject: "Chemistry",
    TeacherName: "Kavita Sharma",
    Location: "Jabalpur",
    GroupCode: "N3G7KR",
    Description: "Mastering complex mathematical equations and theories.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2019/01/29/16/51/periodic-system-3962844_640.jpg",
    DetailedDescription:
      "Immerse yourself in the captivating world of atoms, molecules, and reactions in our chemistry chat. Discuss topics such as chemical bonding, kinetics, and organic chemistry with fellow enthusiasts. Our video call feature facilitates virtual lab experiments and molecular modeling, providing immersive learning experiences from the comfort of your home.",
    Topics: ["chemical bonding", "kinetics", "organic chemistry"],
  },
  {
    StudyGroupId: 38,
    GroupName: "Equation Experts",
    Rating: 4.6,
    TeacherExperienceYears: 10,
    Subject: "Math",
    TeacherName: "Suresh Singh",
    Location: "Gwalior",
    GroupCode: "U6J2TF",
    Description: "Cultivating expertise in plant biology and ecology.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2020/09/24/16/50/board-5599231_640.png",
    DetailedDescription:
      "Embark on a mathematical adventure in our mathematics chat, where you'll explore the beauty and intricacies of numbers and patterns. Engage in discussions on topics like calculus, algebra, and geometry with peers and mentors. With video calls, visualize abstract concepts and collaborate on problem-solving sessions, honing your mathematical skills.",
    Topics: ["calculus", "algebra", "geometry"],
  },
  {
    StudyGroupId: 39,
    GroupName: "Anatomy Aficionados",
    Rating: 4.1,
    TeacherExperienceYears: 6,
    Subject: "Biology",
    TeacherName: "Kirti Sharma",
    Location: "Vijayawada",
    GroupCode: "M1C5RV",
    Description: "Excelling in the art of coding and software engineering.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2013/11/20/09/36/virus-213708_640.jpg",
    DetailedDescription:
      "Explore the wonders of life in our biology chat, where you'll delve into the complexities of living organisms and ecosystems. Discuss topics such as genetics, evolution, and ecology with fellow biologists. Our video call feature enables virtual dissections and field trips, providing hands-on learning experiences in the world of biology.",
    Topics: ["genetics", "ecology", "evolutionary biology"],
  },
  {
    StudyGroupId: 40,
    GroupName: "Hacker Heroes",
    Rating: 4.7,
    TeacherExperienceYears: 11,
    Subject: "Coding",
    TeacherName: "Raman Kumar",
    Location: "Jodhpur",
    GroupCode: "G9W4NJ",
    Description: "Studying the intricacies of physiological processes.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2018/05/17/08/34/matrix-3408060_640.jpg",
    DetailedDescription:
      "Unlock the power of technology in our coding chat, where you'll learn to write code and build software applications. From programming languages to algorithms, explore coding concepts with guidance from experienced developers. With video calls, engage in live coding sessions and collaborative projects, accelerating your journey to becoming a proficient coder.",
    Topics: ["programming languages", "algorithms"],
  },
  {
    StudyGroupId: 41,
    GroupName: "History Scholars",
    Rating: 4.4,
    TeacherExperienceYears: 8,
    Subject: "History",
    TeacherName: "Anjali Tiwari",
    Location: "Madurai",
    GroupCode: "7X3LQP",
    Description: "Scripting the future through coding and programming.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2017/09/07/16/50/acropolis-2725918_1280.jpg",
    DetailedDescription:
      "Dive into the depths of human history in our history chat, where you'll explore ancient civilizations, cultural movements, and pivotal events. Discuss topics such as wars, revolutions, and societal changes with fellow history enthusiasts. With video calls, analyze primary sources and historical artifacts, gaining insights into the past that continue to shape our present.",
    Topics: [
      "ancient civilizations",
      "cultural movements",
      "pivotal events",
      "wars",
      "revolutions",
    ],
  },
  {
    StudyGroupId: 42,
    GroupName: "Geography Explorers",
    Rating: 4.2,
    TeacherExperienceYears: 6,
    Subject: "Geography",
    TeacherName: "Vikram Singh",
    Location: "Raipur",
    GroupCode: "V2H6AU",
    Description:
      "Gaining insights into historical narratives and their impact.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2016/08/24/14/29/earth-1617121_640.jpg",
    DetailedDescription:
      "Embark on a virtual exploration of our planet's diverse landscapes, cultures, and environments in our geography chat. Discuss topics such as physical geography, human geography, and geopolitical issues with peers. Our video call feature enables interactive map analysis and virtual field trips, providing a deeper understanding of the world around us.",
    Topics: ["physical geography", "human geography", "geopolitical issues"],
  },
  {
    StudyGroupId: 43,
    GroupName: "Physics Kings",
    Rating: 4.5,
    TeacherExperienceYears: 9,
    Subject: "Physics",
    TeacherName: "Meenakshi Gupta",
    Location: "Kota",
    GroupCode: "S7N4KP",
    Description: "Navigating the landscapes of Earth and beyond.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2013/11/17/14/16/einstein-212102_640.jpg",
    DetailedDescription:
      "Join our physics chat to journey through the wonders of the universe, from the microscopic realm of particles to the vast expanse of space. Engage in discussions on topics such as mechanics, thermodynamics, and quantum physics with experts and enthusiasts. With video calls, witness experiments and simulations, gaining a deeper insight into the laws governing our reality.",
    Topics: ["mechanics", "thermodynamics", "quantum physics"],
  },
  {
    StudyGroupId: 44,
    GroupName: "Formula Fanatics",
    Rating: 4.3,
    TeacherExperienceYears: 7,
    Subject: "Chemistry",
    TeacherName: "Ajay Sharma",
    Location: "Chandigarh",
    GroupCode: "B3V8TG",
    Description: "Delving into the mysteries of particle physics.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2024/02/09/16/24/test-8563353_640.jpg",
    DetailedDescription:
      "Immerse yourself in the captivating world of atoms, molecules, and chemical reactions in our chemistry chat. Explore topics such as chemical kinetics, equilibrium, and organic chemistry with fellow learners. Our video call feature enables virtual lab experiments and molecular modeling, allowing for hands-on exploration and understanding of chemical principles.",
    Topics: ["atoms", "molecules", "chemical reactions"],
  },
  {
    StudyGroupId: 45,
    GroupName: "Logic Legends",
    Rating: 4.8,
    TeacherExperienceYears: 12,
    Subject: "Math",
    TeacherName: "Kiran Singh",
    Location: "Guwahati",
    GroupCode: "Q6M2ZE",
    Description: "Building foundations in mathematics and problem-solving.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2020/05/13/15/44/geometry-5167943_640.jpg",
    DetailedDescription:
      "Embark on a journey of discovery through the fascinating realm of mathematics in our chat. Explore topics such as calculus, algebra, and geometry with peers and mentors. Engage in collaborative problem-solving sessions and discussions, with the support of our video call feature for visualizing abstract concepts and applications in real-world scenarios.",
    Topics: ["calculus", "algebra", "geometry", "problem-solving"],
  },
  {
    StudyGroupId: 46,
    GroupName: "Physiology Pioneers",
    Rating: 4.6,
    TeacherExperienceYears: 10,
    Subject: "Biology",
    TeacherName: "Anamika Gupta",
    Location: "Solapur",
    GroupCode: "D1K5FS",
    Description: "Mastering the use of calculators for mathematical tasks.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2017/11/11/11/30/chemistry-2938901_640.jpg",
    DetailedDescription:
      "Explore the diversity and complexity of life on Earth in our biology chat. Dive into topics such as genetics, ecology, and evolutionary biology with fellow enthusiasts. Our video call feature facilitates virtual dissections, field trips, and microscopy sessions, providing immersive learning experiences and a deeper understanding of biological concepts.",
    Topics: ["genetics", "ecology", "evolutionary biology"],
  },
  {
    StudyGroupId: 47,
    GroupName: "Scripting Sages",
    Rating: 4.2,
    TeacherExperienceYears: 6,
    Subject: "Coding",
    TeacherName: "Rajiv Tiwari",
    Location: "Hubli",
    GroupCode: "8R7W9X",
    Description:
      "Exploring the frontiers of biotechnology and genetic engineering.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2019/03/03/14/38/hacker-4031973_640.jpg",
    DetailedDescription:
      "Unlock the power of programming in our coding chat, where you'll learn to create software solutions and algorithms. Explore programming languages such as Python, Java, and JavaScript with the guidance of experienced developers. With video calls, engage in live coding sessions, code reviews, and collaborative projects to enhance your coding skills.",
    Topics: ["software solutions", "algorithms", "programming languages"],
  },
  {
    StudyGroupId: 48,
    GroupName: "History Scholars",
    Rating: 4.5,
    TeacherExperienceYears: 9,
    Subject: "History",
    TeacherName: "Puja Sharma",
    Location: "Dharwad",
    GroupCode: "L2C6UV",
    Description: "Commanding proficiency in coding and software development.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2015/04/12/16/33/hammer-719066_640.jpg",
    DetailedDescription:
      "Step into the past and uncover the rich tapestry of human civilization in our history chat. Discuss ancient civilizations, significant events, and influential figures with fellow history buffs. With video calls, analyze primary sources and historical artifacts, gaining insights into the socio-cultural, political, and economic forces that have shaped our world.",
    Topics: [
      "ancient civilizations",
      "significant events",
      "influential figures",
    ],
  },
  {
    StudyGroupId: 49,
    GroupName: "Geography Explorers",
    Rating: 4.3,
    TeacherExperienceYears: 7,
    Subject: "Geography",
    TeacherName: "Anil Verma",
    Location: "Bareilly",
    GroupCode: "5P9D4J",
    Description: "Unveiling the secrets of photonics and light.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2016/03/17/23/00/europe-1264062_640.jpg",
    DetailedDescription:
      "Embark on a virtual journey around the globe in our geography chat, where you'll explore the Earth's physical features, environments, and human landscapes. Engage in discussions on topics such as cartography, climate change, and cultural geography with peers and experts. Our video call feature enables interactive map analysis and virtual field trips, providing a deeper understanding of geographical concepts and phenomena.",
    Topics: ["Earth's physical features", "environments", "human landscapes"],
  },
  {
    StudyGroupId: 50,
    GroupName: "Physics Atomic",
    Rating: 4.7,
    TeacherExperienceYears: 11,
    Subject: "Physics",
    TeacherName: "Ritu Singh",
    Location: "Moradabad",
    GroupCode: "Y7Q3LG",
    Description: "Pioneering advancements in polymer chemistry.",
    ImageURL:
      "https://cdn.pixabay.com/photo/2017/04/03/01/53/einstein-2197302_640.jpg",
    DetailedDescription:
      "Embark on a voyage through the laws governing the universe in our physics chat. Explore topics such as classical mechanics, electromagnetism, and quantum theory with fellow enthusiasts. Engage in lively discussions and problem-solving sessions, supported by our video call feature for visual demonstrations and experiments, ensuring a comprehensive understanding of physical phenomena.",
    Topics: ["classical mechanics", "electromagnetism", "quantum theory"],
  },
];
